/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the authelete-pro SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx petUpdatePet.ts
 */

import { AutheletePro } from "authelete-pro";

const autheletePro = new AutheletePro({
  apiKey: process.env["AUTHELETEPRO_API_KEY"] ?? "",
});

async function main() {
  const result = await autheletePro.updatePet({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      "<value 1>",
    ],
  });

  console.log(result);
}

main().catch(console.error);
