workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    authelete pro-OAS:
        inputs:
            - location: ./specs/spec1.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/vartana/qwerty/authelete-pro-oas
targets:
    authelete-pro:
        target: typescript
        source: authelete pro-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/vartana/qwerty/authelete-pro-oas-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
